/**
 * Shared types for the benchmark pipeline.
 *
 * `BenchmarkDefinition` mirrors the shape of `benchmarks/{slug}/benchmark.yaml`.
 * `Manifest` mirrors `benchmarks/benchmarks.json` — the single source of truth
 * the Astro showcase reads at build time.
 *
 * Both the runner (tools/bench) and the site (site/) import from this file.
 * Keep it dependency-free so the site can also pull it in without dragging
 * the bench tooling into its build.
 */

export type SkillsMode = "none" | "default" | "amsterdam"

export type AgentName = "copilot"

/** A single criterion within a rubric category. */
export interface RubricCriterion {
  id: string
  label: string
  max: number
}

/** One scoring category — Design System, Language, Structure, etc. */
export interface RubricCategory {
  label: string
  max: number
  criteria: RubricCriterion[]
}

/** Score-range → human label mapping for the showcase ScoreBadge. */
export interface RatingBand {
  min: number
  max: number
  label: string
  color: "red" | "amber" | "lime" | "green"
}

/**
 * One declared variant for a benchmark — what the runner CAN build.
 * Until the runner has actually built it, no prototype directory exists.
 */
export interface VariantDefinition {
  id: string
  label: string
  agent: AgentName
  model: string
  skills: SkillsMode
}

/** Top-level benchmark.yaml shape. */
export interface BenchmarkDefinition {
  id: string
  slug: string
  name: string
  difficulty: "beginner" | "intermediate" | "advanced"
  persona: string
  skillsTested: string[]
  prompt: string
  variants: VariantDefinition[]
  rubric: Record<string, RubricCategory>
  ratings: RatingBand[]
  rationale?: string[]
}

/**
 * Per-criterion score the LLM judge or a human writes back.
 * Human notes live in `notes`; structured numbers live in `score`.
 */
export interface CriterionScore {
  criterionId: string
  score: number
  notes?: string
}

/** Aggregated score for one prototype across all rubric categories. */
export interface PrototypeScore {
  total: number
  max: number
  byCategory: Record<string, { score: number; max: number }>
  criteria: CriterionScore[]
  /** "human" if scored manually, "llm" if scored by `bun bench judge`. */
  source: "human" | "llm"
  /** When the score was assigned. */
  scoredAt: string
  /** For LLM scores: the model and prompt hash used. */
  llmModel?: string
  llmPromptHash?: string
}

/**
 * Per-prototype meta.json — written by the runner alongside index.html.
 * Lives at: benchmarks/{slug}/prototypes/{variantId}/meta.json
 */
export interface PrototypeMeta {
  benchmarkId: string
  benchmarkSlug: string
  variantId: string
  variantLabel: string
  agent: AgentName
  model: string
  skills: SkillsMode
  /**
   * Hash of the prompt the runner actually fed to the agent.
   * If this drifts from benchmark.yaml's prompt, the prototype is stale.
   */
  promptHash: string
  /** ISO timestamp when the runner finished. */
  builtAt: string
  /** Wall-clock duration of the agent run, in milliseconds. */
  durationMs: number
  /** Token usage if the agent reported it (some agents only emit aggregated metrics — see `usage` below). */
  tokens?: {
    input?: number
    output?: number
    total?: number
  }
  /**
   * Agent-specific usage metrics. Copilot CLI reports these instead of tokens:
   *   - premiumRequests:    count of model requests that count against the user's quota
   *   - apiDurationMs:      total time spent in model API calls
   *   - sessionDurationMs:  wall-clock duration of the entire copilot session
   *   - linesAdded / linesRemoved / filesModified: code-change statistics
   */
  usage?: {
    premiumRequests?: number
    apiDurationMs?: number
    sessionDurationMs?: number
    linesAdded?: number
    linesRemoved?: number
    filesModified?: number
  }
  /** True if the agent succeeded on the first attempt without needing a retry. */
  oneShot: boolean
  /** Path (relative to the prototype dir) to the agent's session transcript. */
  sessionTranscript?: string
  /** Path (relative to the prototype dir) to the iframable entry point. */
  entry: string
  /** Score, if a human or the judge has written one. May be absent on fresh runs. */
  score?: PrototypeScore
  /** Any free-form notes the runner or judge wants to surface. */
  notes?: string
  /** Anything else the runner wants to record. */
  extra?: Record<string, unknown>
}

/**
 * Showcase manifest — the single file the Astro site reads at build time.
 * Generated by `bun bench manifest` from disk.
 */
export interface Manifest {
  /** ISO timestamp when the manifest was generated. */
  generatedAt: string
  /** Manifest schema version — bump on breaking changes. */
  version: 1
  benchmarks: ManifestBenchmark[]
}

export interface ManifestBenchmark {
  /** Source-of-truth definition copied verbatim from benchmark.yaml. */
  definition: BenchmarkDefinition
  /** All prototype directories that exist on disk for this benchmark. */
  prototypes: PrototypeMeta[]
  /** Optional legacy screenshots for benchmarks that pre-date the runner. */
  legacyScreenshots?: LegacyScreenshot[]
}

export interface LegacyScreenshot {
  variantLabel: string
  /** Path relative to benchmarks/{slug}/. */
  path: string
}
